### ISSUE TITLE
Overall Project Plan

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/nz-band-sensitivity#1]
**Usage of RAIL.creation and RAIL.estimation (and tomographers?)**
 - [ ] Define conditions of wide-field sample
 - [ ] Define conditions of training sample
 - [ ] Generate these samples with RAIL.creation
 - [ ] Estimate p(z) with existing rail.Estimator subclasses (FlexZBoost, BPZ, dummies).
 - [ ] Choose tomographer(s) to use
 - [ ] Run the samples through tomographers, using the different band subsets (riz, griz, ugrizy)

**Development of n(z) estimators**
 - [ ] Decide whether to make a new RAIL.summarization subpackage or to subclass rail.Estimator into nz-estimator and pz-estimator.
 - [ ]  Implement rail.Summarizer superclass and dummy stacked p(z) method.
 - [ ] Wrap [Koukoufilippas' DIR n(z) implementation](https://github.com/nikfilippas/DIR_calibration) as rail.Summarizers
 - [ ] Wrap [qit implementation of CHIPPR](https://github.com/LSSTDESC/qit/) as rail.Summarizers.

**Metrics**
 - [ ] Choose and implement the computation metrics.
 - [ ] Design and build a pipeline for running tomographers and n(z) estimators such that computation and science metrics can be evaluated along the way (built on the tomo_challenge scripts).
 - [ ] Choose and implement any additional post-n(z) metrics that aren't already in the tomo challenge scripts.
 - [ ] Add more metrics of 1D PDFs (including n(z)) to RAIL.evaluation (possibly by implementing in qp and calling through RAIL.evaluation; nearly ready to start)
